# Definition of decks Robin DR401
# Version 1.0.0
# This is at layout level
# default-text-bg-color: (40, 40, 40)
default-label-color: blue
default-label-font: DIN Medium.ttf
default-label-size: 13
default-text-size: 24
default-label-position: ct
default-vibrate: SHORT
default-icon-color: (94, 111, 130)
default-annunciator-style: k
cockpit-color: black
cockpit-text-color: khaki
